name: tdigest-ekg
version: "0"
synopsis: TDigests for ekg
description: TDigests for ekg
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-mega-repo
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

library:
  default-extensions:
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - ScopedTypeVariables
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - ekg-core
    - focus
    - futurice-prelude
    - servant-server
    - stm
    - stm-containers
    - tdigest
