name: smileys-app
version: "0"
synopsis: Smileys backend for FutuHours
description: Smileys backend for FutuHours
author: Jussi Vaihia <jussi.viahia@futurice.com>
maintainer: Jussi Vaihia <jussi.viahia@futurice.com>
license: BSD3
github: futurice/haskell-mega-rpo
category: Web
tested-with: GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ScopedTypeVariables

library:
  source-dirs: src
  dependencies:
    - base                  >=4.7   && <4.10
    - aeson
    - aeson-compat
    - base-compat
    - Chart
    - containers
    - dynmap-cache
    - env-config
    - fum-client
    - futurice-foundation
    - futurice-prelude
    - futurice-reports
    - futurice-servant
    - generics-sop
    - http-client
    - http-client-tls
    - http-types
    - lens
    - lucid
    - planmill-client
    - postgresql-simple
    - resource-pool
    - servant
    - servant-Chart
    - servant-lucid
    - servant-server
    - swagger2
    - text
    - time
    - vector


executables:
  smileys-app-server:
    ghc-options: -threaded -rtsopts
    main: Main.hs
    source-dirs: srv
    dependencies:
      - base
      - smileys-app
