name: servant-Chart
version: "0"
synopsis: Servant support for Chart
description: Servant support for Chart
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/servant-Chart-svg
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base           >=4.7      && <4.10
  - Chart
  - Chart-diagrams
  - diagrams-lib
  - diagrams-svg
  - file-embed
  - http-media     >=0.6.2    && <0.7
  - servant        >=0.4.4.5  && <0.11
  - swagger2
  - svg-builder
  - SVGFonts

library:
  source-dirs: src
