-- CREATE SCHEMA planmillproxy;

-------------------------------------------------------------------------------
-- Generic cache for planmill queries
-------------------------------------------------------------------------------

CREATE TABLE planmillproxy.cache (
  query TEXT PRIMARY KEY,
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  viewed INT NOT NULL DEFAULT 0,
  data BYTEA NOT NULL
);
