name: haxl-fxtra
version: 0.0.0.0
synopsis: Futurice extras for Haxl
description: |
  Mostly bindings to various datasources
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: futurice/haskell-haxl-fxtra
category: Web
tested-with: GHC==7.8.4, GHC==7.10.2
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base                  >=4.7      && <4.10
  - base-compat           >=0.6.0    && <0.10
  - haxl                  >=0.3      && <0.4
  - http-client           >=0.4.18.1 && <0.5
  - http-client-tls       >=0.2.2    && <0.3
  - text                  >=1.2.0.6  && <1.3
  - hashable              >=1.2.3.3  && <1.3
  - parallel-io           >=0.3.3    && <0.4
  - github                >=0.14.0
  - fum-client
  - flowdock-rest         >=0.2.0.0
  - bytestring
  - exceptions
  - vector
  - bifunctors
  - tagged
  - haxl-typed

library:
  source-dirs: src
